MxOnline/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""MxOnline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
import xadmin
from django.views.static import serve  # 处理静态文件

from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView
from users.views import LogoutView, IndexView
from organization.views import OrgView
from MxOnline.settings import MEDIA_ROOT
# from MxOnline.settings import STATIC_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    # 利用Django本身自带TemplateView处理静态文件文件
    url('^$', IndexView.as_view(), name='index'),  # 调用此方法即可自动转换出view方法
    # 只需要指定index文件 # 这样就不需要写后台的viewDjango就会自动跳转到指定Template
    url('^login/$',LoginView.as_view(), name='login'),

    # 2018/4/12 配置 退出
    url('^logout/$',LogoutView.as_view(), name='logout'),
    # 只是传递句柄  指向这个函数并不是调用它
    url('^register/$', RegisterView.as_view(), name="register"),
    url(r'^captcha/', include('captcha.urls')), # 引入验证码view
    # 处理用户激活 提取传过来的url变量  采用python 分组贪婪匹配 放到active_code中

    # 链接失效 或者链接错误
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),

    url(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),
    # 新的接口 处理重设密码
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset_pwd"),
    # 重置密码
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),

    # 课程机构的url配置 namespace
    # org/作为 organization.urls 路由中的总 路由开头
    url(r'^org/', include('organization.urls', namespace="org")), #使用二级路由 即url的分发

    # 公开课 课程相关url的配置
    url(r'^course/', include('courses.urls', namespace="course")), #使用二级路由 即url的分发


    # 处理media 信息 读取课程机构图片信息【配置上传文件的访问处理函数】
    url(r'^media/(?P<path>.*)$', serve, {'document_root':MEDIA_ROOT}),

    # 解决DEBUG为False的情况 Django不再为系统自行代理  需要Apache之类的代理 可以自行编写处理
    # 处理media 信息 读取课程机构图片信息【配置上传文件的访问处理函数】
    # url(r'^static/(?P<path>.*)$', serve, {'document_root':STATIC_ROOT}),


    # 用户相关url的配置 跳转到 用户app下
    url(r'^users/', include('users.urls', namespace="users")), #使用二级路由 即url的分发


]

# 全局404页面相关配置
handler404 = 'users.views.page_not_found'

# 全局500页面配置
handler500 = 'users.views.page_error'

apps/courses/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/3/29 12:14
# @Author  : maxinehehe
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

from django.conf.urls import url,include

from .views import CourseListView, CourseDetailView, CourseInfoView, CommentsView, AddCommentsView, VideoPlayView


# 柯城列表页的配置
# 可以 先写url 再写view
urlpatterns = [
    # 课程列表页
     url(r'^list/$',CourseListView.as_view() , name='course_list'), # 刚进入更开课 也是课程列表
     # 课程详情页
     url(r'^detail/(?P<course_id>\d+)/$',CourseDetailView.as_view() , name='course_detail'),
     # 课程详情之章节信息
     url(r'^info/(?P<course_id>\d+)/$',CourseInfoView.as_view() , name='course_info'),
     # 课程评论
     url(r'^comment/(?P<course_id>\d+)/$',CommentsView.as_view() , name='course_comments'),
     # 添加课程评论  异步请求
     url(r'^add_comment/$',AddCommentsView.as_view() , name='add_comment'),
     # 视频播放配置
     url(r'^video/(?P<video_id>\d+)/$',VideoPlayView.as_view() , name='video_play'),
    ]

apps/organization/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/1/30 9:49
# @Author  : maxinehehe
# @Site    : 
# @File    : urls.py
# @Software: PyCharm


from django.conf.urls import url,include

from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, AddFavView

from .views import TeacherListView, TeacherDetailView
# 可以 先写url 再写view
urlpatterns = [
    # 课程机构首页 列表页
    url(r'^list/$',OrgView.as_view() , name='org_list'),

    # modelform     # 再次解释as_view()的用法 类操作需要
    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),
    # 课程机构 机构首页
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),
    # 课程机构 机构课程
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name="org_course"),
    # 课程机构 机构介绍
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name="org_desc"),
    # 课程机构 机构讲师 nam便于更改
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name="org_teacher"),

    # 机构收藏
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),
    # 讲师列表页
    url(r'^teacher/list/$', TeacherListView.as_view(), name="teacher_list"),

    # 讲师详情页
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name="teacher_detail"),
    ]

apps/users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/4/7 20:07
# @Author  : maxinehehe
# @Site    : 
# @File    : urls.py
# @Software: PyCharm


from django.conf.urls import url,include

from .views import UserinfoView, UploadImageView, UpdatePwdView, SendEmailCodeView
from .views import UpdateEmailView, MyCourseView, MyFavOrgView, MyFavTeacherView, MyFavCourseView
from .views import MyMessageView

# 柯城列表页的配置
# 可以 先写url 再写view
urlpatterns = [
    # 用户信息
    url(r'^info/$',UserinfoView.as_view() , name='user_info'), # 刚进入更开课 也是课程列表

    # 用户头像上传
    url(r'^image/$',UploadImageView.as_view() , name='image_upload'), # 刚进入更开课 也是课程列表

    # 用户个人中心修改密码
    url(r'^update/pwd/$',UpdatePwdView.as_view() , name='update_pwd'), # 刚进入更开课 也是课程列表

    # 发送邮箱验证码
    url(r'^sendemail_code/$',SendEmailCodeView.as_view() , name='sendemail_code'),

    # 修改邮箱 即收到邮箱验证码之后进行修改
    url(r'^update_email/$',UpdateEmailView.as_view() , name='update_email'),

    # 个人中心 我的课程
    url(r'^mycourse/$',MyCourseView.as_view() , name='mycourse'),

    # 我收藏的课程机构
    url(r'^myfav/org/$',MyFavOrgView.as_view() , name='myfav_org'),

    # 我收藏的课程讲师
    url(r'^myfav/teacher/$',MyFavTeacherView.as_view() , name='myfav_teacher'),

    # 我收藏的课程
    url(r'^myfav/course/$',MyFavCourseView.as_view() , name='myfav_course'),

    url(r'^mymessage/$',MyMessageView.as_view() , name='mymessage'),

    ]

apps/courses/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
import os
from organization.models import CourseOrg, Teacher

# current_path = os.path.dirname(os.path.realpath(__file__))+'/'
# print "----------------------------->",current_path
# Create your models here.
'''
课程models   即对课程页面的设计  包括表之间的对应关系
'''


class Course(models.Model):
    # 增添属性 新添加字段 必须null=True以防止新添加字段出错
    course_org = models.ForeignKey(CourseOrg, verbose_name=u"课程机构", null=True) # 外键为[指向]course_org
    # 课程名称
    name = models.CharField(max_length=50, verbose_name=u"课程名")
    desc = models.CharField(max_length=100, verbose_name=u"课程描述")
    detail = models.TextField(verbose_name=u"课程详情")   # 暂时命名textFiled  富文本

    # 设置区分轮播广告位 标志
    is_banner = models.BooleanField(default=False, verbose_name=u"是否轮播")

    # 添加该课程·讲师 外键 8-5 日期 4/4
    teacher = models.ForeignKey(Teacher, verbose_name=u"讲师", null=True, blank=True)
    degree = models.CharField(choices=(("cj","初级"), ("zj","中级"), ("gj","高级")), max_length=2, verbose_name=u"难度")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长（分钟数）")
    # 课程 学习人数
    students = models.IntegerField(default=0, verbose_name=u"学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name=u"收藏人数")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面图", max_length=100) # current_path+
    # 统计课程点击量[非开始学习]  可用于计算转化量
    click_nums = models.IntegerField(default=0, verbose_name=u"点击数")
    # 新添加 课程目录 4/2操作
    category = models.CharField(default=u"后端开发", max_length=20, verbose_name=u"课程类别")
    # 8-3添加 查询某一门课程的相关课程  或随机选一个
    tag = models.CharField(default="", verbose_name=u"课程标签", max_length=10, null=True, blank=True)
    # 课程须知  8-5 日期 4/4
    youneed_know = models.TextField(default="", max_length=300, verbose_name=u"课程须知", null=True, blank=True)
    # 老师告诉你能学到什么 8-5 日期 4/4
    teacher_tell = models.TextField(default="", max_length=300, verbose_name=u"老师告诉你能学到什么？", null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    # Meta信息
    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name

    # 后期统计章节数 新添加 4/2
    def get_zj_nums(self):
        # 获取课程章节数
        # 当有外键指向course时 course可以反向取出该数据
        return self.lesson_set.all().count()   # 【queryset】返回所有的课程
    get_zj_nums.short_description = u"章节数"   # 该函数称为列的短描述

    # 点击 get_zj_nums之后 跳转
    # def go_to(self):
    #     from django.utils.safestring import mark_safe
    #     return mark_safe("<a href='http://www.baidu.com'>跳转</>")
    # go_to.short_description = u"跳转"   # 该函数称为列的短描述  若要显示 需添加到CourseAdmin vs1
    # 获取学习课程的人数【用于课程详情页】
    def get_learn_nums(self):
        return self.usercourse_set.all()[:6] # 最多取6个显示

    def get_course_lesson(self):
        # 获取课程所有章节
        return self.lesson_set.all()

    def __unicode__(self):
        return self.name


# 数据库的一对多 多对一 在Django中则是外键的映射


class Lesson(models.Model):
    '''
        课程model设计
    '''
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name

    def get_lesson_video(self):
        # 获取章节视频
        # 通过video指向lesson的外键 找到课程的video
        return self.video_set.all()

    def __unicode__(self):
        return self.name

class Video(models.Model):
    '''
        视频model设计
    '''
    # 指向lesson的外键
    lesson = models.ForeignKey(Lesson, verbose_name=u"章节")
    name = models.CharField(max_length=100, verbose_name=u"视频名称")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长（分钟数）")
    url = models.CharField(default="", max_length=200, verbose_name=u"访问地址")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

class CourseResource(models.Model):
    '''
        课程资源model设计
    '''
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"视频名称")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name=u"资源文件", max_length=100)  # 可以直接生成上传按钮
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

templates/active_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>链接错误</title>
</head>
<body>
链接错误或者失效了！
</body>
</html>

templates/index.html
{# 继承base.html#}
{% extends 'base.html' %}
{% block title %} 课程机构列表 - 微慕课在线网 {% endblock %}

{% load staticfiles %}

{% block custom_bread %}

{% endblock %}

{% block custom_js %}
     <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}

{% block content %}
        <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banner %}
                                <li>
                                    <a href="{{ banner.url }}">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}


						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/module1_1.jpg"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                {% for banner_course in banner_courses %}
                                    <li>
                                        <a href="{% url 'course:course_detail' banner_course.id %}">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_course.image }}" />
                                        </a>
                                    </li>
                                {% endfor %}
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for course in courses %}
                                <div class="module1_{{ forloop.counter|add:2 }} box">
                                    {#forloop.counter从1开始|add:2表示在1基础上＋2 即为3  forloop.counter0表示从0开始  #}
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="django入门">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                            {% endfor %}


					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for org in courses_orgs %}
                                <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                    {# divisibleby:5 表示能够被5整除 #}
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}

						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}


templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程-微慕课在线学习网{% endblock %}

{% block custom_bread %}
     <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
     <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                     <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li ><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for fav_course in course_list %}
                            <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' fav_course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ fav_course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' fav_course.id %}"><h2>{{ fav_course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ fav_course.learm_times }}</i></span>
                                <span class="fr">学习人数：{{ fav_course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ fav_course.Course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ fav_course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
{% endblock %}


templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程-微慕课在线学习网{% endblock %}

{% block custom_bread %}
     <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li ><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in org_list %}
                        <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor  %}

                </div>
            </div>
        </div>
{% endblock %}


templates/usercenter-info.html
{% extends 'usercenter-base.html' %}
{% block title %}个人信息-微慕课在线学习网{% endblock %}

{% block custom_bread %}
     <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:image_upload' %}" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                        {% csrf_token %}
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name }}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birday" value="{{ request.user.birday|date:"Y-m-d"|default_if_none:'' }}" readonly="readonly"/>
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="male" {% if request.user.gender == 'male' %}checked="checked"{% endif %} >男</label>
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="female" {% if request.user.gender == 'female' %}checked="checked"{% endif %}>女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address }}" maxlength="20">
						    <i class="error-tips"></i>
                        </li>
						<li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.mobile|default_if_none:'' }}" maxlength="11">
                        </li>
                        <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        	<input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email }}"/>
                            <span class="green changeemai_btn">[修改]</span>
                    	</li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
						</li>
					</ul>
                    {% csrf_token %}
				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/usercenter-mycourse.html
{% extends 'usercenter-base.html' %}
{% block title %}我的课程-微慕课在线学习网{% endblock %}

{% block custom_bread %}
     <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
       <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for user_course in user_courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' user_course.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ user_course.course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' user_course.course.id %}"><h2>{{ user_course.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ user_course.course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ user_course.course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ user_course.course.course_org.name }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ user_course.course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}




				</div>
			</div>
		</div>
	</div>
{% endblock %}
